//card and section headers;
var globalAdvancedHeader             = 'Advanced settings';
var globalChooseTypeHeader           = 'Available Connector types';
var globalConfigErrorHeader          = 'Configuration error';
var globalConfigHeader               = 'Connector configuration';
var globalConfigListHeader           = 'Configured Connectors';
var globalConfirmHeader              = 'Confirm action';
var globalConnectorListHeader        = 'Other Connectors';
var globalCustomIconHeader           = 'Connector icon';
var globalErrorHeader                = 'Config error';
var globalHelpHeader                 = 'Help';
var globalSettingsHeader             = 'Settings';
var globalShowHeader                 = 'Record';
var globalUnparsedHeader             = 'Unparsed content';
var globalWelcomeHeader              = 'Welcome to Cardin for Gmail!';

//titles;
var globalAuthTypeErrorTitle         = 'Auth type mismatch';
var globalConfigErrorWidgetTitle     = '';
var globalConfirmWidgetTitle         = '';
var globalCustomWidgetFieldTitle     = 'Field';
var globalCustomWidgetIconTitle      = 'Connector icon';
var globalCustomWidgetNameTitle      = 'Connector name';
var globalErrorWidgetTitle           = 'Error description';
var globalExtraDataTitle             = '';
var globalHelpWidgetTitle            = '';
var globalNoDataWidgetTitle          = 'No content';
var globalOrderingWidgetTitle        = 'Sort by';
var globalResetWidgetTitle           = 'Reset';
var globalUnparsedDataWidgetTitle    = 'Unparsed content';
var globalUnparsedErrorWidgetTitle   = 'Parse failure reason';
var globalWelcomeWidgetTitle         = '';

//content - errors;
var globalAuthTypeErrorContent       = 'The Connector seems to require OAuth 2.0 authorization to work, but you set auth type to "none". Please configure OAuth properties in Settings';
var globalConfigErrorWidgetContent   = 'Seems like you have a configuration issue! Please, reset the Add-on if this is the only section you see. Otherwise, try removing any malformed Connectors before resetting';
var globalConnectorListErrorContent  = 'An error occured during Connector list generation';

//content;
var globalAuthTextWidgetContent      = 'The Connector requires authorization to an external service. You can revoke authorization any time by clicking "revoke". Note that either action will trigger a refresh';
var globalConfirmRemoveWidgetContent = 'The Connector will be permanently removed. Are you sure?';
var globalConfirmResetWidgetContent  = 'Every configured Connector will be permanently deleted. Are you sure?';
var globalCustomWidgetAuthText       = 'Authorization type';
var globalCustomWidgetSwitchText     = 'Manually invoke Connector';
var globalExtraDataText              = 'More data is available, but we trimmed it to avoid hitting the 100 field limit';
var globalHelpWidgetContent          = 'Visit our website for setup instructions and other support resources';
var globalIsDefaultWidgetSwitchText  = 'Run and display by default';
var globalNoDataWidgetContent        = 'The Connector response has no content to display for';
var globalNotAuthorizedContent       = 'Seems like the Connector you built has to be authorized or there was a change in required permissions and you need to reauthorize or you lost access';
var globalOptionalFieldsContent      = 'These fields are optional and can be left blank';
var globalOrderingWidgetContent      = 'Choose how to sort your configured Connectors (order of creation by default)';
var globalResetWidgetContent         = 'Every user preference will be reset, and Connector configurations will be deleted';
var globalRevokeWidgetContent        = 'If you wish to uninstall Cardin for Gmail from your account, tick the checkbox below';
var globalWelcomeWidgetContent       = 'Click on a Connector from the list below to get started';

//hints;
var globalCustomWidgetNameHint       = 'Name to display in list of Connectors';
var globalCustomIconHint             = 'Icon URL (public) to set to Connector';

//button as labels texts;
var globalAuto                       = 'Auto';
var globalError                      = 'Error';
var globalManual                     = 'Manual';
var globalNoData                     = 'No data';
var globalSuccess                    = 'Success';

//button texts;
var globalCancelText                 = 'Cancel';
var globalCardinUrlText              = 'cardinsoft.com';
var globalClearWidgetSubmitText      = 'Clear';
var globalConfirmText                = 'Confirm';
var globalCreateConnectorText        = 'Create';
var globalLoadExtraBackText          = 'Back';
var globalLoadExtraForwardText       = 'Next';
var globalLoginText                  = 'Login';
var globalOpenAuthText               = 'Authorize';
var globalRemoveConnectorText        = 'Remove';
var globalResetWidgetSubmitText      = 'Reset';
var globalRevokeAuthText             = 'Revoke';
var globalRootText                   = 'Go back';
var globalUpdateConnectorText        = 'Update';
var globalUpdateShowText             = 'Update';

//URLs;
var globalCardinUrl                  = 'https://cardinsoft.com/cardin-gmail/';
var globalCardinIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/cardin-logo.png';
var globalCustomIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/custom.png';
var globalFlowIconUrl                = 'https://cardinsoft.github.io/outlook/assets/flow.png';
var globalGitHubIconUrl              = 'https://cardinsoft.github.io/outlook/assets/github.png';
var globalInfusionIconUrl            = 'https://cardinsoft.com/wp-content/uploads/2019/03/infusionsoft.png';
var globalPipedriveIconUrl           = 'https://cardinsoft.github.io/outlook/assets/Pipedrive.png';
var globalSheetsIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/sheets.png';
var globalYouTubeUrl                 = 'https://youtube.com/';

//notifications, warnings and error messages
var globalClearSuccess               = 'Cache successfully cleared!';
var globalCreateFailure              = 'Connector creation failed';
var globalCreateSuccess              = 'Connector successfully created!';
var globalInvalidURLnoMethod         = 'URLs should include http or https and a domain';
var globalRemoveFailure              = 'Connector removal failed';
var globalRemoveSuccess              = 'Connector successfully removed!';
var globalResetFailure               = 'Add-on configuration reset failed!';
var globalResetSuccess               = 'Add-on configuration successfully reset!';
var globalRevokeAccessSuccess        = 'Access token successfully revoked!';
var globalUpdateFailure              = 'Connector update failed';
var globalUpdateSuccess              = 'Connector successfully updated!';

//field names;
var globalBaseClassName              = 'Connector';
var globalClientIdFieldName          = 'id';
var globalCustomNameName             = 'custom';
var globalCustomUrlUrl               = '';
var globalDefaultFieldName           = 'isDefault';
var globalEnumCheckbox               = 'CHECK_BOX';
var globalEnumDropdown               = 'DROPDOWN';
var globalEnumRadio                  = 'RADIO_BUTTON';
var globalIconFieldName              = 'icon';
var globalManualFieldName            = 'manual';
var globalNameFieldName              = 'name';
var globalOrderTypeFieldName         = 'order';
var globalOrderReverseFieldName      = 'reverse';
var globalRedirectFieldName          = 'redirect';
var globalScopeFieldName             = 'scope';
var globalSecretFieldName            = 'secret';
var globalUrlAuthFieldName           = 'urlAuth';
var globalURLfieldName               = 'url';
var globalUrlTokenFieldName          = 'urlToken';

//parameters;
var globalIncludeGitHub              = false;
var globalInfusionsoftApptsCap       = 5;
var globalInfusionsoftTasksCap       = 5;
var globalNumUncollapsible           = 5;
var globalNumUncollapsibleList       = 3;
var globalTextButtonActionAction     = 'action';
var globalTextButtonActionClick      = 'click';
var globalTextButtonActionLink       = 'link';
var globalWidgetsCap                 = 50;

//OAuth2 flow;
var globalAlreadyAuthorized          = 'Connector previously authorized!';
var globalAlreadyRevoked             = 'Connector revoked or does not have access!';
var globalAuthFailure                = 'Authorization failed!';
var globalAuthorize                  = 'Please authorize the Connector';
var globalAuthSuccess                = 'Successfully authorized!';
var globalAuthUrlInputHint           = 'Authorization URL';
var globalClientIdInputHint          = 'Obtained from API';
var globalRevokeAccess               = 'Revoke access';
var globalScopeInputHint             = 'Obtained from API';
var globalSecretInputHint            = 'Obtained from API';
var globalTokenUrlInputHint          = 'Token URL';

//connector types specific globals;
var globalGitHubShort                = 'Retrieves basic user info from GitHub account if one exists';
var globalFlowShort                  = 'Sends and recieves data from Microsoft Flow - this Connector type can work with iterative data updating';
var globalInfusionShort              = 'Fetches sales and marketing information from Infusionsoft by Keap CRM & marketing automation platform';
var globalPipedriveShort             = 'Fetches sales and marketing data from Pipedrive Sales CRM & Pipeline Management';
var globalSheetsShort                = 'Fetches and displays data from a Google Sheet. Please, make sure that you have access rights to view it';
var globalQBShortDesc                = 'Fetches customer or supplier invoice or bill detail from connected QB company. Please authenticate to QB';