//card and section headers;
var globalActivitiesHeader           = 'Activities';
var globalAdvancedHeader             = 'Advanced';
var globalChooseTypeHeader           = 'Add a new Connector';
var globalConfigAuthHeader           = 'Authorization config';
var globalConfigErrorHeader          = 'Configuration error';
var globalConfigHeader               = 'Connector configuration';
var globalConfigAdvancedHeader       = 'Advanced configuration';
var globalConfigListHeader           = 'Edit existing Connectors';
var globalConfirmHeader              = 'Confirm action';
var globalConnectorErrorHeader       = 'Connector error';
var globalConnectorListHeader        = 'Other Connectors';
var globalCompanyInfoHeader          = 'Company info';
var globalContactInfoHeader          = 'Contact info';
var globalCustomIconHeader           = 'Connector icon';
var globalDashboardHeader            = 'Dashboard';
var globalEmploymentContactHeader    = 'Employment';
var globalEmploymentCompanyHeader    = 'Business';
var globalErrorHeader                = 'Config error';
var globalHelpHeader                 = 'Help';
var globalNotAuthorizedHeader        = 'Not authorized';
var globalPreferencesHeader          = 'Options';
var globalResourceHeader             = 'Resources';
var globalSettingsHeader             = 'Settings';
var globalShowHeader                 = 'Record';
var globalUnparsedHeader             = 'Unparsed content';
var globalWelcomeHeader              = 'Welcome to Cardin!';

//titles;
var globalAuthTypeApiTokenTitle      = 'API token auth';
var globalAuthTypeErrorTitle         = 'Auth type mismatch';
var globalAuthTypeUserCredTitle      = 'User Credentials';
var globalConfigErrorWidgetTitle     = '';
var globalConfirmWidgetTitle         = '';
var globalContactSupportTitle        = 'Contact support';
var globalCustomWidgetFieldTitle     = 'Field';
var globalCustomWidgetIconTitle      = 'Connector icon';
var globalCustomWidgetNameTitle      = 'Connector name';
var globalErrorWidgetTitle           = 'Error description';
var globalExtraDataTitle             = '';
var globalHelpWidgetTitle            = '';
var globalNoConnectorsWidgetTitle    = 'No Connectors';
var globalNoDataWidgetTitle          = 'No content';
var globalOrderingWidgetTitle        = 'Sort by';
var globalResetWidgetTitle           = 'Reset';
var globalSkipAuthWidgetTitle        = 'Skip check';
var globalUnparsedDataWidgetTitle    = 'Unparsed content';
var globalUnparsedErrorWidgetTitle   = 'Parse failure reason';
var globalWelcomeWidgetTitle         = '';

//content - errors;
var globalAuthTypeErrorContent       = 'The Connector seems to require OAuth 2.0 authorization to work, but you set auth type to "none". Please configure OAuth properties in Settings';
var globalConfigErrorWidgetContent   = 'Seems like you have a configuration issue! Please, reset the Add-on if this is the only section you see. Otherwise, try removing any malformed Connectors before resetting';
var globalConnectorListErrorContent  = 'An error occured during Connector list generation';
var globalGeneralErrorContent        = 'Unfortunately, the Connector encountered an error. Please, see details provided below for troubleshooting';

//custom icons;
var globalIconAccount                = 'https://cardinsoft.com/wp-content/uploads/2019/07/ACCOUNT.png';
var globalIconActivities             = 'https://cardinsoft.com/wp-content/uploads/2019/08/ACTIVITIES.png';
var globalIconAddressShip            = 'https://cardinsoft.com/wp-content/uploads/2019/07/ADDRESS-SHIP.png';
var globalIconAddressBill            = 'https://cardinsoft.com/wp-content/uploads/2019/07/ADDRESS-BILL.png';
var globalIconBackArrow              = 'https://cardinsoft.com/wp-content/uploads/2019/07/BACKWARD.png';
var globalIconBackground             = 'https://cardinsoft.com/wp-content/uploads/2019/06/BACKGROUND.png';
var globalIconBirthday               = 'https://cardinsoft.com/wp-content/uploads/2019/07/BIRTHDAY.png';
var globalIconCall                   = 'https://cardinsoft.com/wp-content/uploads/2019/07/CALL.png';
var globalIconCallInbound            = 'https://cardinsoft.com/wp-content/uploads/2019/08/PHONE-IN.png';
var globalIconCallOutbound           = 'https://cardinsoft.com/wp-content/uploads/2019/08/PHONE-OUT.png';
var globalIconCallMissed             = 'https://cardinsoft.com/wp-content/uploads/2019/08/CALL-MISSED.png';
var globalIconCallEnded              = 'https://cardinsoft.com/wp-content/uploads/2019/07/CALL-ENDED.png';
var globalIconClockRecurrent         = 'https://cardinsoft.com/wp-content/uploads/2019/08/CLOCK-RECURR.png';
var globalIconCompany                = 'https://cardinsoft.com/wp-content/uploads/2019/07/COMPANY.png';
var globalIconCompanyParent          = 'https://cardinsoft.com/wp-content/uploads/2019/08/COMPANY-PARENT.png';
var globalIconCustom                 = 'https://cardinsoft.com/wp-content/uploads/2019/06/CUSTOM.png';
var globalIconDeal                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL.png';
var globalIconDealClose              = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-CLOSE.png';
var globalIconDealCloseCurrent       = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-CLOSE-CUR.png';
var globalIconDealInc                = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-INC.png';
var globalIconDealIncCurrent         = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-INC-CUR.png';
var globalIconDealLost               = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-LOST.png';
var globalIconDealLostCurrent        = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-LOST-CUR.png';
var globalIconDealOpen               = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-OPEN.png';
var globalIconDealQual               = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-QUAL.png';
var globalIconDealQualCurrent        = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-QUAL-CUR.png';
var globalIconDealWon                = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-WON.png';
var globalIconDealWonCurrent         = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-WON-CUR.png';
var globalIconDealUnqual             = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-UNQUAL.png';
var globalIconDealUnqualCurrent      = 'https://cardinsoft.com/wp-content/uploads/2019/08/DEAL-UNQUAL-CUR.png';
var globalIconDepartment             = 'https://cardinsoft.com/wp-content/uploads/2019/07/DEPARTMENT.png';
var globalIconDialpad                = 'https://cardinsoft.com/wp-content/uploads/2019/07/DIALPAD.png';
var globalIconDirectEmail            = 'https://cardinsoft.com/wp-content/uploads/2019/07/DIRECT-EMAIL.png';
var globalIconDirectPhone            = 'https://cardinsoft.com/wp-content/uploads/2019/07/DIRECT-PHONE.png';
var globalIconEdit                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/EDIT.png';
var globalIconFacebook               = 'https://cardinsoft.com/wp-content/uploads/2019/06/FACEBOOK.png';
var globalIconFaxPhone               = 'https://cardinsoft.com/wp-content/uploads/2019/07/FAX.png';
var globalIconFlag                   = 'https://cardinsoft.com/wp-content/uploads/2019/07/FLAG.png';
var globalIconForwardArrow           = 'https://cardinsoft.com/wp-content/uploads/2019/07/FORWARD.png';
var globalIconHot                    = 'https://cardinsoft.com/wp-content/uploads/2019/08/HOT.png';
var globalIconGoogle                 = 'https://cardinsoft.com/wp-content/uploads/2019/07/GOOGLE-SIGNIN-SQ.png';
var globalIconGoogleFull             = 'https://cardinsoft.com/wp-content/uploads/2019/07/GOOGLE-SIGNIN.png';
var globalIconIndustry               = 'https://cardinsoft.com/wp-content/uploads/2019/07/INDUSTRY.png';
var globalIconInviteRecurrent        = 'https://cardinsoft.com/wp-content/uploads/2019/08/INVITE-RECURR.png';
var globalIconJobTitle               = 'https://cardinsoft.com/wp-content/uploads/2019/07/JOB-TITLE.png';
var globalIconLink                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/LINK.png';
var globalIconList                   = 'https://cardinsoft.com/wp-content/uploads/2019/07/LIST.png';
var globalIconLostInfo               = 'https://cardinsoft.com/wp-content/uploads/2019/08/LOST-INFO.png';
var globalIconMissedMeeting          = 'https://cardinsoft.com/wp-content/uploads/2019/07/MEETING-MISSED.png';
var globalIconMobilePhone            = 'https://cardinsoft.com/wp-content/uploads/2019/07/MOBILE-PHONE.png';
var globalIconNotes                  = 'https://cardinsoft.com/wp-content/uploads/2019/08/NOTES.png';
var globalIconNumber                 = 'https://cardinsoft.com/wp-content/uploads/2019/08/NUMBER.png';
var globalIconHide                   = 'https://cardinsoft.com/wp-content/uploads/2019/07/HIDE.png';
var globalIconHomeEmail              = 'https://cardinsoft.com/wp-content/uploads/2019/07/HOME-EMAIL.png';
var globalIconHomePhone              = 'https://cardinsoft.com/wp-content/uploads/2019/07/HOME-PHONE.png';
var globalIconMobileEmail            = 'https://cardinsoft.com/wp-content/uploads/2019/07/MOBILE-EMAIL.png';
var globalIconOfficeEmail            = 'https://cardinsoft.com/wp-content/uploads/2019/07/OFFICE-EMAIL.png';
var globalIconOverdue                = 'https://cardinsoft.com/wp-content/uploads/2019/08/OVERDUE.png';
var globalIconReset                  = 'https://cardinsoft.com/wp-content/uploads/2019/08/RESET.png';
var globalIconSearch                 = 'https://cardinsoft.com/wp-content/uploads/2019/08/SEARCH.png';
var globalIconSend                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/SEND.png';
var globalIconShow                   = 'https://cardinsoft.com/wp-content/uploads/2019/07/SHOW.png';
var globalIconSkype                  = 'https://cardinsoft.com/wp-content/uploads/2019/06/SKYPE.png';
var globalIconSwitch                 = 'https://cardinsoft.com/wp-content/uploads/2019/08/SWITCH.png';
var globalIconTab                    = 'https://cardinsoft.com/wp-content/uploads/2019/06/TAB.png';
var globalIconTask                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/TASK.png';
var globalIconTaskDone               = 'https://cardinsoft.com/wp-content/uploads/2019/08/TASK-DONE.png';
var globalIconTaskFailed             = 'https://cardinsoft.com/wp-content/uploads/2019/08/TASK-FAILED.png';
var globalIconText                   = 'https://cardinsoft.com/wp-content/uploads/2019/08/TEXT.png';
var globalIconTwitter                = 'https://cardinsoft.com/wp-content/uploads/2019/06/TWITTER.png';
var globalIconTwitterCircle          = 'https://cardinsoft.com/wp-content/uploads/2019/08/TWITTER-CIRCLE.png';
var globalIconWebhook                = 'https://cardinsoft.com/wp-content/uploads/2019/06/WEBHOOK.png';
var globalIconWorkPhone              = 'https://cardinsoft.com/wp-content/uploads/2019/07/WORK-PHONE.png';
var globalIconWebsite                = 'https://cardinsoft.com/wp-content/uploads/2019/07/WEBSITE.png';

//content;
var globalAuthTextWidgetContent      = 'The Connector requires authorization to an external service. You can revoke authorization any time by clicking "revoke". Note that either action will trigger a refresh';
var globalConfirmRemoveWidgetContent = 'The Connector will be permanently removed. Are you sure?';
var globalConfirmResetWidgetContent  = 'Every configured Connector will be permanently deleted. Are you sure?';
var globalCustomWidgetAuthText       = 'Authorization type';
var globalCustomWidgetSwitchText     = 'Manually invoke Connector';
var globalExtraDataText              = 'More data is available, but we trimmed it to avoid hitting the 100 field limit';
var globalHelpWidgetContent          = 'Visit our website for setup instructions and other support resources';
var globalIsDefaultWidgetSwitchText  = 'Run and display by default';
var globalNoConnectorsContent        = 'Seems like you have no Connectors configured. Please, choose a type from the list below';
var globalNoDataWidgetContent        = 'The Connector response has no content to display for';
var globalNotAuthorizedContent       = 'Seems like the Connector you built has to be authorized or there was a change in required permissions and you need to reauthorize or you lost access';
var globalOptionalFieldsContent      = 'These fields are optional and can be left blank';
var globalOrderingWidgetContent      = 'Choose how to sort your configured Connectors (order of creation by default)';
var globalResetWidgetContent         = 'Every user preference will be reset, and Connector configurations will be deleted';
var globalRevokeWidgetContent        = 'If you wish to uninstall Cardin from your account, tick the checkbox below';
var globalSkipAuthWidgetContent      = 'You can authorize Connectors anytime in Settings. If you wish to skip the check, simply toggle the option below';
var globalWelcomeWidgetContent       = 'Please choose a Connector from the list below to start viewing and editing the associated contact data stored in that app';

//hints;
var globalCustomWidgetNameHint       = 'Name to display in list of Connectors';
var globalCustomIconHint             = 'Icon URL (public) to set to Connector';

//button as labels texts;
var globalAuto                       = 'Auto';
var globalError                      = 'Error';
var globalManual                     = 'Manual';
var globalNoData                     = 'No data';
var globalSuccess                    = 'Success';

//button texts;
var globalAddContactText             = 'Add contact';
var globalAddContactInCRMText        = 'Add contact in CRM';
var globalCancelText                 = 'Cancel';
var globalCardinUrlText              = 'cardinsoft.com';
var globalClearWidgetSubmitText      = 'Clear';
var globalConfirmText                = 'Confirm';
var globalCreateConnectorText        = 'Create';
var globalLoadExtraBackText          = 'Back';
var globalLoadExtraForwardText       = 'Next';
var globalLoginText                  = 'Login';
var globalOpenAuthText               = 'Authorize';
var globalRefreshText                = 'Refresh';
var globalRemoveConnectorText        = 'Remove';
var globalResetWidgetSubmitText      = 'Reset';
var globalRevokeAuthText             = 'Revoke';
var globalRootText                   = 'Go back';
var globalUpdateConnectorText        = 'Update';
var globalUpdateShowText             = 'Update';

//product icon URLs;
var globalBpmIconUrl                 = 'https://cardinsoft.com/wp-content/uploads/2019/06/bpm.png';
var globalCardinIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/cardin-logo.png';
var globalCloseIconUrl               = 'https://cardinsoft.com/wp-content/uploads/2019/07/Close.png';
var globalCloudFuncIconUrl           = 'https://cardinsoft.com/wp-content/uploads/2019/07/Google-Cloud-Functions.png';
var globalCustomIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/custom.png';
var globalEnterIconUrl               = 'https://cardinsoft.com/wp-content/uploads/2019/05/enter.png';
var globalFlowIconUrl                = 'https://cardinsoft.com/wp-content/uploads/2019/03/flow.png';
var globalGitHubIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/github.png';
var globalIftttIconUrl               = 'https://cardinsoft.com/wp-content/uploads/2019/07/IFTTT.png';
var globalInfusionIconUrl            = 'https://cardinsoft.com/wp-content/uploads/2019/03/infusionsoft.png';
var globalLACRMiconUrl               = 'https://cardinsoft.com/wp-content/uploads/2019/04/LACRM.png';
var globalOneCRMiconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/07/1CRM.png';
var globalPipedriveIconUrl           = 'https://cardinsoft.com/wp-content/uploads/2019/03/pipedrive.png';
var globalQuickBooksIconUrl          = 'https://cardinsoft.com/wp-content/uploads/2019/02/VqEjTc4a_400x400.jpg';
var globalSheetsIconUrl              = 'https://cardinsoft.com/wp-content/uploads/2019/03/sheets.png';
var globalYouTubeUrl                 = 'https://youtube.com/';
var globalZendeskSellIconUrl         = 'https://cardinsoft.com/wp-content/uploads/2019/07/Zendesk.png';

//notifications, warnings and error messages
var globalClearSuccess               = 'Cache successfully cleared!';
var globalCreateFailure              = 'Connector creation failed';
var globalCreateSuccess              = 'Connector successfully created!';
var globalInvalidURLnoMethod         = 'URLs should include http or https and a domain';
var globalRemoveFailure              = 'Connector removal failed';
var globalRemoveSuccess              = 'Connector successfully removed!';
var globalResetFailure               = 'Add-on configuration reset failed!';
var globalResetSuccess               = 'Add-on configuration successfully reset!';
var globalRevokeAccessSuccess        = 'Access token successfully revoked!';
var globalUpdateFailure              = 'Connector update failed';
var globalUpdateSuccess              = 'Connector successfully updated!';

//field names;
var globalApiTokenTokenFieldName     = 'apitoken';
var globalApiTokenUserFieldName      = 'usercode';
var globalBaseClassName              = 'Connector';
var globalClientIdFieldName          = 'id';
var globalCustomNameName             = 'custom';
var globalCustomUrlUrl               = '';
var globalDefaultFieldName           = 'isDefault';
var globalIconFieldName              = 'icon';
var globalManualFieldName            = 'manual';
var globalNameFieldName              = 'name';
var globalOrderTypeFieldName         = 'order';
var globalOrderReverseFieldName      = 'reverse';
var globalRedirectFieldName          = 'redirect';
var globalScopeFieldName             = 'scope';
var globalSecretFieldName            = 'secret';
var globalUrlAuthFieldName           = 'urlAuth';
var globalURLfieldName               = 'url';
var globalUrlTokenFieldName          = 'urlToken';

//Enum references;
var globalEnumCheckbox               = 'CHECK_BOX';
var globalEnumReplyDraft             = 'REPLY_AS_DRAFT';
var globalEnumDropdown               = 'DROPDOWN';
var globalEnumRadio                  = 'RADIO_BUTTON';
var globalEnumStandalone             = 'STANDALONE_DRAFT';

//Widget types (except SelectionInput which accepts Enum type);
var globalButtonSet                  = 'ButtonSet';
var globalImage                      = 'Image';
var globalImageButton                = 'ImageButton';
var globalKeyValue                   = 'KeyValue';
var globalTextButton                 = 'TextButton';
var globalTextInput                  = 'TextInput';
var globalTextParagraph              = 'TextParagraph';

//Global widgets configurations;
var globalWidgetSeparator            = {type: globalKeyValue,content: '\r'};

//Action types;
var globalActionAction               = 'action';
var globalActionAuth                 = 'auth';
var globalActionClick                = 'click';
var globalActionCompose              = 'compose';
var globalActionLink                 = 'link';

//parameters;
var includeConnectorsInDev           = true;
var globalAnalyticsTesting           = true;
var globalInfusionsoftApptsCap       = 5;
var globalInfusionsoftTasksCap       = 5;
var globalNumUncollapsible           = 5;
var globalNumUncollapsibleList       = 3;
var globalWidgetsCap                 = 25;

//Sign in flow;
var globalAccountInfoHeader          = 'Account Info';
var globalCardinAccountHeader        = 'Cardin account';
var globalCurrentPasswordHeader      = 'Password';
var globalGeneralInfoHeader          = 'General Info';
var globalLinkedSignInHeader         = 'Linked Sign In';
var globalMyAccountHeader            = 'My Account';
var globalPasswordHeader             = 'Current password';
var globalPreferencesHeader          = 'Preferences';
var globalRemindHeader               = 'Remind password';
var globalSignInHeader               = 'Sign in';
var globalSignUpHeader               = 'Sign up';
var globalSignInGoogleContent        = 'Sign in with Google';

//OAuth2 flow;
var globalAlreadyAuthorized          = 'Connector previously authorized!';
var globalAlreadyRevoked             = 'Connector revoked or does not have access!';
var globalAuthFailure                = 'Authorization failed!';
var globalAuthorize                  = 'Please authorize the Connector';
var globalAuthSuccess                = 'Successfully authorized!';
var globalAuthUrlInputHint           = 'Authorization URL';
var globalClientIdInputHint          = 'Obtained from API';
var globalRevokeAccess               = 'Revoke access';
var globalScopeInputHint             = 'Obtained from API';
var globalSecretInputHint            = 'Obtained from API';
var globalTokenUrlInputHint          = 'Token URL';

//Auth types;
var globalUserCredentials            = 'UserCred';
var globalApiTokenAuthType           = 'APItoken';
var globalOAuth2AuthType             = 'OAuth2';

//connector types specific globals;
var globalBpmShort                   = 'Fetches sales and marketing info from bpm\'online CRM platform';
var globalCloseShort                 = 'Fetches contact and activities information from Close CRM';
var globalGitHubShort                = 'Retrieves basic user info from GitHub account if one exists';
var globalInfusionShort              = 'Fetches sales and marketing information from Infusionsoft by Keap CRM & marketing automation platform';
var globalLACRMshort                 = 'Fetches contact and pipeline information from Less Annoying CRM';
var globalOneCRMshort                = 'Fetches contact information from 1CRM platform';
var globalPipedriveShort             = 'Fetches sales and marketing data from Pipedrive Sales CRM & Pipeline Management';
var globalSheetsShort                = 'Fetches data from a Google Sheet. Please, make sure that you have access rights to view it';
var globalQBShortDesc                = 'Fetches customer or supplier invoice or bill detail from connected QuickBooks company. Please authenticate to QuickBooks';
var globalWebhookShort               = 'Sends and recieves data from custom webhooks, including Microsoft Flow (supports iterative data updating)';
var globalZendeskSellShort           = 'Fetches contact and company information from Zendesk Sell';